#!/bin/sh
#---------------------------------------------------------------------------------------------------
# Implementation of "Vegas Mode" on the mangOH Yellow, which blinks the software-controlled LEDs.
# This is intentionally a very CPU intensive way to do this that uses a lot of the Legato framework
# so it can be used to identify opporunities for optimization.
#
# The environment variable VEGAS_MODE_USLEEP can be used to set the number of microseconds to
# sleep between colour changes.  The default is zero.
#
# Copyright (C) Sierra Wireless Inc.
#---------------------------------------------------------------------------------------------------

sleepUS=0

echo "VEGAS_MODE_USLEEP = $VEGAS_MODE_USLEEP"

if [ "$VEGAS_MODE_USLEEP" ]
then
    if echo "$VEGAS_MODE_USLEEP" | egrep "^[0-9]+$" > /dev/null
    then
        sleepUS=$VEGAS_MODE_USLEEP
    else
        echo "Invalid number of microseconds in VEGAS_MODE_USLEEP: '$VEGAS_MODE_USLEEP'" >&2
        exit 1;
    fi
fi

SetColour()
{
    blue=`expr $1 % 2`
    green=`expr $1 / 2 % 2`
    red=`expr $1 / 4 % 2`

    if [ $blue -eq 1 -o $green -eq 1 -o $red -eq 1 ]
    then
        off=0
    else
        off=1
    fi

    dhubPush /app/leds/tri/red/enable $red
    dhubPush /app/leds/tri/green/enable $green
    dhubPush /app/leds/tri/blue/enable $blue
    dhubPush /app/leds/mono/enable $off
}

# Trap SIGINT or SIGTERM and turn off all the LEDs before exiting.
trap 'SetColour 0; dhubPush /app/leds/mono/enable false; exit 0' 2 15

colour=0

while true
do
    SetColour $colour
    usleep $sleepUS
    colour=`expr $colour + 1`
done
